### ISSUE TITLE
Too much battery usage

### ISSUE THREAD

**Issue by Ledaa** [anselm94/Torchie-Android#1]
When accessibilty is on, there is far too much battery usage.

**Comment by haarp** [comment]
Can confirm. Unfortunately, there is probably no way to avoid this when you want screen-off functionality :(

https://github.com/anselm94/Torchie-Android/wiki/How-does-Torchie-work%3F

> At screen off, 'Torchie Quick' starts playing a zero-volume music to keep the processor awake.

**Comment by zamber** [comment]
Isn't the timer option in _Settings_ for _Screen Off_ supposed to partially prevent that?

**Comment by anselm94** [comment]
Closing the issue. The battery drain has been optimized much better than the original implementation in 2016. Please feel free to re-open the issue, if the problem persists
