### ISSUE TITLE
XML error when building in Android Studio

### ISSUE THREAD

**Issue by petia-davidova** [anselm94/Torchie-Android#17]
When I try building the app in Android Studio I get errors for the XML file values_It/strings.xml. There are two resources tags.

**Comment by anselm94** [comment]
Can you please try again by pulling the latest code? If still not fixed, please try doing 'Clean Project' before running the build.

**Comment by anselm94** [comment]
Closing the project for now. In case of any issues, please feel free to reopen the issue again
