### ISSUE TITLE
v3.0 build errors on F-Droid

### ISSUE THREAD

**Issue by relan** [anselm94/Torchie-Android#18]
v3.0 [fails](https://f-droid.org/wiki/page/in.blogspot.anselmbros.torchie/lastbuild_28) to build on F-Droid. Steps to reproduce: run `gradle assembleRelease`.

First issue is that `com.android.tools.build:gradle:3.0.0` is available in the new Google Maven repo, not JCenter. Solution: add `google()` to the `repositories` sections of the root `build.gradle`.

Second issue is failing `lintVitalRelease` task: `Error: Non-translatable resources should only be defined in the base values/ folder`. Solution: fix those errors _or_ disable them (add `checkReleaseBuilds false` into `build.gradle`) _or_ make them non-fatal (add `abortOnError false` into `build.gradle`).

**Comment by anselm94** [comment]
Hello,
Both the issues are fixed now! :)

**Comment by relan** [comment]
Great! F-Droid will pull the next release automatically when it's out.

**Comment by anselm94** [comment]
@relan Can you trigger a rebuild for Torchie at F-Droid? [https://f-droid.org/en/packages/in.blogspot.anselmbros.torchie/](https://f-droid.org/en/packages/in.blogspot.anselmbros.torchie/) doesn't point to latest release

**Comment by relan** [comment]
Do you mean 3.1? Just tag a release and F-Droid will build it.

**Comment by anselm94** [comment]
That's cool! Thanks @relan
