### ISSUE TITLE
Language options not responding when changed

### ISSUE THREAD

**Issue by blackmaryline** [anselm94/Torchie-Android#21]
#### Expected behavior
Language options should change when trying other language options

#### Actual behavior
I tried changing my language options from English language to other language options like espanol, French, Deutsch etc but nothing changes. English language remained the only language it displays

#### How to reproduce
Download Torchie application from Android playstore, go to settings, try other languages apart from default English language, it won't work.

* Browser: Google Chrome updated version
* Operating system: Android 7.0 Nougatt
* Phone: Techno Camon CX Air

#### Recording Of The Bug
https://youtu.be/QaqP5tIFSdw

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@timmyeu/language-options-not-responding-when-changed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by anselm94** [comment]
@blackmaryline Yes. It indeed is a bug. Will be removing that feature for now. However, the application language can be changed by changing the System-language, with the future release
