### ISSUE TITLE
Add an option to disable lockscreen while listening to music or making calls

### ISSUE THREAD

**Issue by CrimsonFork** [anselm94/Torchie-Android#27]
The new workaround is highly reliable. Too reliable, I'd say. I have to completely unlock my phone in order to change any output source.

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by anselm94** [comment]
@OffifialMITX Is this related with this #25 issue? Where the volume slider (with Chromecast icon) in the lock screen?

**Comment by CrimsonFork** [comment]
Yes it actually is. Sorry, I didn't think skipped that one because it is about something else first.

**Comment by anselm94** [comment]
Not a problem!
