### ISSUE TITLE
A pulsating noise heard in 'Screen off' state when enabled for 'Screen off' in some devices

### ISSUE THREAD

**Issue by anselm94** [anselm94/Torchie-Android#4]
Some users reported that they hear some pulsating/static noise when in screen off, only when the functionality is enabled for Screen off. Not all the devices shows this effect.

Torchie plays a zero-volume music to play music. See [How Torchie works?](https://github.com/anselm94/Torchie-Android/wiki/How-does-Torchie-work%3F). May be that's causing an issue?

**Comment by zamber** [comment]
Electrical interference can produce static in speakers when they're not properly shielded.

**Comment by anselm94** [comment]
@zamber Particularly HTC phones with 'BoomSound' reports this issue

**Comment by anselm94** [comment]
This issue has been fixed with Torchie 3.0! Enjoy!
