### ISSUE TITLE
Turns on if on button and volume button pressed together

### ISSUE THREAD

**Issue by snelltheta** [anselm94/Torchie-Android#5]
This wouldn't be much of an issue if 

It didn't happen 
Or, if there was a setting to make it so that only volume buttons turn it on or off.

**Comment by anselm94** [comment]
May be that Power button wakes the system first and turns the flash on, since both the volume buttons are held

**Comment by snelltheta** [comment]
But both volume buttons are not held and it turns on.

**Comment by zamber** [comment]
Can't reproduce on OnePlus Two with stock 5.1.1. @snelltheta, what device are you using? Also, please provide clear reproduction steps (including settings you changed, if any). having a logcat would be stellar too.

**Comment by smichel17** [comment]
I also can't reproduce, on Galaxy S6 (SM-G920A) with 7.0.

**Comment by anselm94** [comment]
Closing the issue, as the reporter has not come back in a long time. Moreover it's not reproducible in other phones.
@snelltheta Please feel free to re-open this issue, if the problem persists.
